[build]
  command = "npm install"
  publish = "."  # مكان ملف index.html
  functions = "netlify/functions" # مكان وظائف Netlify

[functions]
  # تغيير التجميع إلى 'zip' لحل مشكلة 'Could not resolve "firebase-admin"'
  node_bundler = "zip"